CUSTOM_NAME=lackminer-qbtc
CUSTOM_VERSION=0.2.1
CUSTOM_CONFIG_FILENAME=${CUSTOM_CONFIG_FILENAME:-/hive/miners/custom/lackminer-qbtc/miner.conf}
CUSTOM_LOG_BASENAME=${CUSTOM_LOG_BASENAME:-/var/log/miner/lackminer-qbtc/miner}
